### ISSUE TITLE
App crash when Fav size empy and show

### ISSUE THREAD

**Issue by kkdai** [kkdai/ptt-beauty-linebot#9]
Empty Fav
-> Press show Fav
-> No response

**Comment by kkdai** [comment]
error log

```

2023-02-01T04:09:01.397970+00:00 app[web.1]: goroutine 162 [running]:
2023-02-01T04:09:01.397970+00:00 app[web.1]: net/http.(*conn).serve.func1()
2023-02-01T04:09:01.397971+00:00 app[web.1]: /tmp/codon/tmp/cache/go1.17.13/go/src/net/http/server.go:1802 +0xb9
2023-02-01T04:09:01.397971+00:00 app[web.1]: panic({0xaba1c0, 0x116c010})
2023-02-01T04:09:01.397971+00:00 app[web.1]: /tmp/codon/tmp/cache/go1.17.13/go/src/runtime/panic.go:1047 +0x266
2023-02-01T04:09:01.397971+00:00 app[web.1]: github.com/kkdai/linebot-ptt-beauty/bots.actionShowFavorite(0xc0001c9ba0, {0xc0004dc050, 0xc0007996c0}, 0xc00021a3c0)
2023-02-01T04:09:01.397972+00:00 app[web.1]: /tmp/build_9008419b/bots/pttbot.go:254 +0xa9c
2023-02-01T04:09:01.397972+00:00 app[web.1]: github.com/kkdai/linebot-ptt-beauty/bots.actionHandler(0xc0000c80a7, {0xc0000c80a7, 0x13}, 0x6)
2023-02-01T04:09:01.397972+00:00 app[web.1]: /tmp/build_9008419b/bots/pttbot.go:152 +0x1a6
2023-02-01T04:09:01.397973+00:00 app[web.1]: github.com/kkdai/linebot-ptt-beauty/bots.postbackHandler(0xc0001c9ba0)
2023-02-01T04:09:01.397973+00:00 app[web.1]: /tmp/build_9008419b/bots/pttbot.go:392 +0x110
2023-02-01T04:09:01.397973+00:00 app[web.1]: github.com/kkdai/linebot-ptt-beauty/bots.callbackHandler({0xc95368, 0xc0002a2540}, 0x0)
2023-02-01T04:09:01.397973+00:00 app[web.1]: /tmp/build_9008419b/bots/pttbot.go:131 +0x54f
2023-02-01T04:09:01.397974+00:00 app[web.1]: net/http.HandlerFunc.ServeHTTP(0x0, {0xc95368, 0xc0002a2540}, 0xc0002a2540)
2023-02-01T04:09:01.397974+00:00 app[web.1]: /tmp/codon/tmp/cache/go1.17.13/go/src/net/http/server.go:2047 +0x2f
2023-02-01T04:09:01.397974+00:00 app[web.1]: net/http.(*ServeMux).ServeHTTP(0x0, {0xc95368, 0xc0002a2540}, 0xc000374500)
2023-02-01T04:09:01.397975+00:00 app[web.1]: /tmp/codon/tmp/cache/go1.17.13/go/src/net/http/server.go:2425 +0x149
2023-02-01T04:09:01.397975+00:00 app[web.1]: net/http.serverHandler.ServeHTTP({0xc93c98}, {0xc95368, 0xc0002a2540}, 0xc000374500)
2023-02-01T04:09:01.397975+00:00 app[web.1]: /tmp/codon/tmp/cache/go1.17.13/go/src/net/http/server.go:2879 +0x43b
2023-02-01T04:09:01.397976+00:00 app[web.1]: net/http.(*conn).serve(0xc000034fa0, {0xc990a0, 0xc0004b27b0})
2023-02-01T04:09:01.397976+00:00 app[web.1]: /tmp/codon/tmp/cache/go1.17.13/go/src/net/http/server.go:1930 +0xb08
2023-02-01T04:09:01.397976+00:00 app[web.1]: created by net/http.(*Server).Serve
2023-02-01T04:09:01.397977+00:00 app[web.1]: /tmp/codon/tmp/cache/go1.17.13/go/src/net/http/server.go:3034 +0x4e8
```
